// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('turnon', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('turnon', async function() {
    await driver.get("http://192.168.0.1/")
    await driver.findElement(By.id("Password")).click()
    await driver.findElement(By.id("Password")).sendKeys("77470942")
    await driver.findElement(By.css(".submitBtn")).click()
    await driver.findElement(By.linkText("Advanced settings")).click()
    await driver.findElement(By.linkText("Wireless")).click()
    await driver.findElement(By.linkText("Wireless signal")).click()
    await driver.findElement(By.id("fmRbtn-Enable24")).click()
    await driver.findElement(By.id("commonApply")).click()
    {
      const element = await driver.findElement(By.id("commonApply"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.linkText("Log out")).click()
    await driver.close()
  })
})
